# -*- coding: utf-8 -*-
"""smart_manufacturing_final_organized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-Zd1T3Mr58arog33NL44qmSgqIeyzhS

## 1. Import Libraries

# Predictive Maintenance



## Project objective
Predict whether a machine requires maintenance using its sensor and machine-condition data.

### Notebook structure
1. EDA
2. Data preprocessing and statistics
3. Encoding
4. Time-based train/test split
5. Logistic Regression
6. Random Forest
7. Lightgbm
8. Stacking
9. ROC-AUC comparison


> **Important:** `timestamp` is used to preserve chronological order, but is not a model predictor. Potential leakage variables are inspected during EDA and excluded from the final predictive models.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency


from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import StackingClassifier


from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit

pd.set_option('display.max_columns', None)
sns.set_theme(style='whitegrid')

"""## 2. Load Dataset"""

df = pd.read_csv('smart_manufacturing_data.csv')

print("Dataset shape:", df.shape)
df.head(5)

"""## 3. Exploratory Data Analysis (EDA)

### 3.1 Dataset Information
"""

print("Columns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

"""### 3.2 Missing Values and Duplicates"""

print("Missing values:")
print(df.isnull().sum())

print("\nTotal missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

"""### 3.3 Descriptive Statistics"""

df.describe()

"""### Correlation Matrix"""

# Extract numerical features + target (if target is encoded as 0/1 or numeric)
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Compute correlation matrix
num_corr = df[num_cols].corr(method='pearson')

# Plot numerical correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(num_corr, annot=True, fmt='.2f', cmap='coolwarm', vmin=-1, vmax=1, linewidths=0.5)
plt.title('Numerical Correlation Matrix', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

cols = [ 'failure_type', 'maintenance_required']

corr = pd.DataFrame(index=cols, columns=cols)

for x in cols:
    for y in cols:
        table = pd.crosstab(df[x], df[y])
        chi2 = chi2_contingency(table)[0]
        n = table.values.sum()
        corr.loc[x, y] = np.sqrt(chi2 / n / min(table.shape[0]-1, table.shape[1]-1))

corr = corr.astype(float)

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm')
plt.title("Correletaion Matrix")
plt.show()

average_sensor_readings_anomaly = df.groupby(['machine_id', 'anomaly_flag'])[['temperature', 'vibration', 'humidity','pressure', 'energy_consumption']].mean()
display(average_sensor_readings_anomaly)

df = df.drop(columns='energy_consumption')

"""### 3.4 Target Distribution"""

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='maintenance_required')
plt.title('Maintenance Required Distribution')
plt.xlabel('Maintenance Required')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

"""The target distribution is checked before modelling because class imbalance can affect accuracy, recall, and F1-score. We will report more than accuracy when evaluating the classifiers.

### 3.5 Sensor Histograms
"""

sensor_cols = [
    'temperature',
    'vibration',
    'humidity',
    'pressure',
    #'energy_consumption',
    'predicted_remaining_life'
]

for col in sensor_cols:
    plt.figure(figsize=(7,4))
    sns.histplot(data=df, x=col, kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

"""### `predicted_remaining_life`

This histogram displays the distribution of `predicted_remaining_life` for machines that require maintenance (`maintenance_required = 1`). Machines with a lower predicted remaining life (e.g., less than 50 days) are strong candidates for proactive maintenance.

### 3.6 Boxplots — Outlier Detection
"""

for col in sensor_cols:
    plt.figure(figsize=(7,3.5))
    sns.boxplot(data=df, x=col)
    plt.title(f'Boxplot of {col}')
    plt.xlabel(col)
    plt.tight_layout()
    plt.show()

"""### 3.8 Sensor Features vs Maintenance Required"""

for col in sensor_cols:
    plt.figure(figsize=(7,4))
    sns.boxplot(data=df, x='maintenance_required', y=col)
    plt.title(f'{col} vs Maintenance Required')
    plt.xlabel('Maintenance Required')
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()

"""### 3.9 Categorical Features vs Maintenance Required"""

# Convert machine status to readable labels for visualization only.
status_labels = {
    0: 'Idle',
    1: 'Running',
    2: 'Failure'
}

df['machine_status_label'] = df['machine_status'].map(status_labels)

plt.figure(figsize=(7,4))
sns.countplot(
    data=df,
    x='machine_status_label',
    hue='maintenance_required'
)
plt.title('Maintenance Required by Machine Status')
plt.xlabel('Machine Status')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,4))
sns.countplot(
    data=df,
    x='failure_type',
    hue='maintenance_required'
)
plt.title('Maintenance Required by Failure Type')
plt.xlabel('Failure Type')
plt.ylabel('Count')
plt.xticks(rotation=25)
plt.tight_layout()
plt.show()

"""### 3.10 Potential Leakage Check"""

plt.figure(figsize=(8, 5))
ax = sns.countplot(
    data=df[df['maintenance_required'] == 1],
    x='anomaly_flag',
    palette='Set2'
)

for container in ax.containers:
    ax.bar_label(container, fmt='%d', padding=3)

plt.title('Anomaly Flag Distribution when Maintenance Required=1', fontsize=14, fontweight='bold')
plt.xlabel('Anomaly Flag (0=No Anomaly, 1=Anomaly)', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.xticks([0, 1], ['No Anomaly', 'Anomaly'])
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Standardize column names
df.columns = df.columns.str.lower().str.replace(' ', '_')

# Select the top 6 machines by record volume for clean grid visualization
top_machines = df['machine_id'].value_counts().head(6).index
df_top = df[df['machine_id'].isin(top_machines)]

# Faceted Count Plot (x: maintenance_req, hue: anomaly_flag, panel: machine_id)
g = sns.catplot(
    data=df_top,
    x='maintenance_required',
    hue='anomaly_flag',
    col='machine_id',
    col_wrap=3,
    kind='count',
    palette='Set1',
    height=3.5,
    aspect=1.2,
)

# Add value annotations on top of each bar
for ax in g.axes.flat:
  for container in ax.containers:
    ax.bar_label(container, fmt='%d', padding=2, fontsize=8)

g.set_axis_labels('Maintenance Required', 'Count')
g.set_titles('Machine ID: {col_name}', fontweight='bold')
g.fig.subplots_adjust(top=0.88)
g.fig.suptitle(
    'Maintenance Req vs. Anomaly Flag Across Machines',
    fontsize=14,
    fontweight='bold',
)

plt.show()

"""### Downtime Risk Distribution for Machines Requiring Maintenance

This graph shows the distribution of **downtime risk** among the top machines where **maintenance is required**. It helps identify which machines have a higher frequency of downtime risk and may require closer monitoring.

"""

# Filter data for maintenance_required = 1 and top machines
df_filtered_maintenance_required = df_top[df_top['maintenance_required'] == 1]

g = sns.catplot(
    data=df_filtered_maintenance_required,
    x='downtime_risk',
    hue='downtime_risk',
    col='machine_id',
    col_wrap=3,
    kind='count',
    palette='magma',
    height=4,
    aspect=1.2,
    order=sorted(df_filtered_maintenance_required['downtime_risk'].unique()),
    legend=False
)

for ax in g.axes.flat:
    for container in ax.containers:
        ax.bar_label(container, fmt='%d', padding=2, fontsize=8)

g.set_axis_labels('Downtime Risk (when Maintenance Required)', 'Count')
g.set_titles('Machine ID: {col_name}', fontweight='bold')
g.fig.subplots_adjust(top=0.9)
g.fig.suptitle(
    'Downtime Risk Distribution for Machines Requiring Maintenance (Top 6 Machines)',
    fontsize=16,
    fontweight='bold'
)

plt.show()

for col in ['anomaly_flag', 'machine_status', 'failure_type', 'downtime_risk']:
    print(f"\n--- {col} ---")
    print(pd.crosstab(
        df[col],
        df['maintenance_required'],
        normalize='index'
    ).round(3))

"""### Leakage decision

The categorical/status variables and operational risk indicators are inspected because they can contain information that directly reflects the maintenance decision.

For the final models, we use the leakage-safe sensor/condition features only:

- temperature
- vibration
- humidity
- pressure
- energy_consumption
- predicted_remaining_life

`timestamp` is also excluded as a predictor.

### Anomaly Rate per Machine ID

This plot shows the percentage of records with `anomaly_flag = 1` for each individual `machine_id`. This helps identify which machines experience anomalies more frequently.
"""

# Calculate anomaly rate per machine_id
anomaly_rate_per_machine = df.groupby('machine_id')['anomaly_flag'].mean() * 100
anomaly_rate_per_machine = anomaly_rate_per_machine.reset_index()
anomaly_rate_per_machine.columns = ['machine_id', 'anomaly_percentage']

# Sort by anomaly percentage for better visualization
anomaly_rate_per_machine = anomaly_rate_per_machine.sort_values(by='anomaly_percentage', ascending=True)

plt.figure(figsize=(12, 7))
ax = sns.barplot(
    data=anomaly_rate_per_machine,
    x='machine_id',
    y='anomaly_percentage',
    palette='plasma'
)

# Add percentage values on top of each bar
for container in ax.containers:
    ax.bar_label(container, fmt='%.2f%%', padding=3, fontsize=8)

plt.title('Anomaly Rate (%) per Machine ID', fontsize=14, fontweight='bold')
plt.xlabel('Machine ID', fontsize=12)
plt.ylabel('Anomaly Percentage (%)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.ylim(0, anomaly_rate_per_machine['anomaly_percentage'].max() * 1.1) # Set y-limit slightly above max for labels
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### 3.12 Time-Series Analysis

Spliiting by day
"""

df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values('timestamp')

daily = (
    df.groupby(df['timestamp'].dt.date)
      .agg(
          temperature=('temperature', 'mean'),
          vibration=('vibration', 'mean'),
          maintenance_rate=('maintenance_required', 'mean')
      )
      .reset_index()
)

daily['timestamp'] = pd.to_datetime(daily['timestamp'])

plt.figure(figsize=(14,5))
plt.plot(daily['timestamp'], daily['temperature'])
plt.title('Average Temperature Over Time')
plt.xlabel('Timestamp')
plt.ylabel('Average Temperature')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(14,5))
plt.plot(daily['timestamp'], daily['vibration'])
plt.title('Average Vibration Over Time')
plt.xlabel('Timestamp')
plt.ylabel('Average Vibration')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(14,5))
plt.plot(daily['timestamp'], daily['maintenance_rate'])
plt.title('Maintenance Required Rate Over Time')
plt.xlabel('Timestamp')
plt.ylabel('Maintenance Rate')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Time-series conclusion
The timestamp is useful for preserving chronological order and checking whether the maintenance pattern changes over time. It is not used directly as a predictor because the EDA does not establish that the timestamp itself is a meaningful cause of maintenance.

## 4. Data Preprocessing and Statistics

### 4.1 Convert Timestamp and Sort
"""

df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values('timestamp').reset_index(drop=True)

"""### 4.2 Statistical Summary of Numerical Features"""

stats = df[sensor_cols].describe().T

stats['median'] = df[sensor_cols].median()
stats['skewness'] = df[sensor_cols].skew()
stats['missing'] = df[sensor_cols].isnull().sum()
stats['missing_%'] = (df[sensor_cols].isnull().mean() * 100).round(2)

stats = stats[
    ['count', 'mean', 'std', 'min', '25%', 'median',
     '50%', '75%', 'max', 'skewness', 'missing', 'missing_%']
]

stats

"""### Preprocessing decision

Extreme sensor readings are retained unless they are confirmed to be data-entry errors. In manufacturing data, unusual temperature or vibration values may represent the exact machine condition we want the model to learn.

Missing values are checked above. If missing values exist, they should be imputed using statistics calculated from the training data only.

## 5. Encoding

Categorical features are encoded **before the modelling stage**.

However, because `machine_status` and `failure_type` were identified as potential leakage variables, they are **not included in the final model feature matrix**.

The encoding section is kept here to document the correct preprocessing method and to satisfy the categorical-data preprocessing requirement.
"""

categorical_cols = ['machine_status', 'failure_type']

encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

encoded = encoder.fit_transform(df[categorical_cols])

encoded_cols = encoder.get_feature_names_out(categorical_cols)

encoded_df = pd.DataFrame(
    encoded,
    columns=encoded_cols,
    index=df.index
)

print("Original categorical columns:", categorical_cols)
print("Encoded columns:")
print(encoded_cols.tolist())

encoded_df.head()

"""### Final modelling features

The encoded categorical variables are **not merged into the final X matrix**, because using them would risk target leakage.

The final models therefore use only:

`temperature`, `vibration`, `humidity`, `pressure`,  `predicted_remaining_life`

## 6. Chronological Train/Test Split
"""

features = [
    'temperature',
    'vibration',
    'humidity',
    'pressure',
    'predicted_remaining_life',

]

# First two months = trainig
# Last month = testing
train = df[df['timestamp'] < '2025-03-01'].copy()
test = df[df['timestamp'] >= '2025-03-01'].copy()

X_train = train[features].copy()
y_train = train['maintenance_required']

X_test = test[features].copy()
y_test = test['maintenance_required']

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

print("\nTrain period:")
print(train['timestamp'].min(), "→", train['timestamp'].max())

print("\nTest period:")
print(test['timestamp'].min(), "→", test['timestamp'].max())

"""### Why no `stratify`?

A random `train_test_split(..., stratify=y)` is not used because this project requires a chronological split. The first two months must remain training data and the final month must remain the test data.

## 7. Logistic Regression
"""

from sklearn.model_selection import RandomizedSearchCV

lr_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('logistic', LogisticRegression(
        max_iter=2000,
        random_state=42,
        class_weight='balanced'
    ))
])

lr_param_dist = {
    'logistic__C': [0.001, 0.01, 0.1, 1, 10, 100],
    'logistic__solver': ['liblinear', 'lbfgs'],
    'logistic__penalty': ['l2']
}

tscv = TimeSeriesSplit(n_splits=3)

lr_search = RandomizedSearchCV(
    lr_pipeline,
    param_distributions=lr_param_dist,
    n_iter=6,
    scoring='f1',
    cv=tscv,
    random_state=42,
    n_jobs=-1
)

lr_search.fit(X_train, y_train)

logistic_model = lr_search.best_estimator_
print("Best parameters:", lr_search.best_params_)

#predict for binary classifc. on test 0-1
lr_pred = logistic_model.predict(X_test)
lr_proba = logistic_model.predict_proba(X_test)[:, 1]

print("Accuracy:", round(accuracy_score(y_test, lr_pred), 4))
print("\nClassification Report:")
print(classification_report(y_test, lr_pred))

# Handle target class imbalance using class weights.
# The chronological train/test split remains unchanged, and the test set is not modified.
print("Training target distribution:")
print(y_train.value_counts())
print("\nTraining target percentages:")
print((y_train.value_counts(normalize=True) * 100).round(2))

"""### Logistic Regression — Confusion Matrix"""

cm_lr = confusion_matrix(y_test, lr_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix — Logistic Regression')
plt.tight_layout()
plt.show()

"""### Logistic Regression — ROC-AUC"""

lr_fpr, lr_tpr, _ = roc_curve(y_test, lr_proba)
lr_auc = roc_auc_score(y_test, lr_proba)

plt.figure(figsize=(7,5))
plt.plot(lr_fpr, lr_tpr, label=f'Logistic Regression (AUC = {lr_auc:.3f})')
plt.plot([0,1], [0,1], '--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve — Logistic Regression')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print("Logistic Regression ROC-AUC:", round(lr_auc, 4))

"""## 8. Random Forest"""

rf_param_dist = {
    'n_estimators': [100, 200],       # dropped 300 — diminishing returns, doubles fit time for little gain
    'max_depth': [10, 20],             # dropped None (unlimited depth = slowest trees)
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt'],          # sqrt is almost always the better choice anyway — no need to search log2 too
    'class_weight': ['balanced']
}

rf_search = RandomizedSearchCV(
    RandomForestClassifier(
        random_state=42,
        n_jobs=-1
    ),
    param_distributions=rf_param_dist,
    n_iter=5,        # was 10 — half the candidates tried
    cv=2,             # was 3 — one fewer fold per candidate
    scoring='f1',
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_search.fit(X_train, y_train)

rf = rf_search.best_estimator_
print("Best params:", rf_search.best_params_)

rf_pred = rf.predict(X_test)
rf_proba = rf.predict_proba(X_test)[:, 1]

print("Accuracy:", round(accuracy_score(y_test, rf_pred), 4))
print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

"""### Random Forest — Confusion Matrix"""

cm_rf = confusion_matrix(y_test, rf_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix — Random Forest')
plt.tight_layout()
plt.show()

"""### Random Forest — ROC-AUC"""

rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_proba)
rf_auc = roc_auc_score(y_test, rf_proba)

plt.figure(figsize=(7,5))
plt.plot(rf_fpr, rf_tpr, label=f'Random Forest (AUC = {rf_auc:.3f})')
plt.plot([0,1], [0,1], '--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve — Random Forest')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print("Random Forest ROC-AUC:", round(rf_auc, 4))

"""### Random Forest Feature Importance"""

importance = (
    pd.Series(rf.feature_importances_, index=features)
    .sort_values(ascending=False)
)

plt.figure(figsize=(8,5))
sns.barplot(x=importance.values, y=importance.index)
plt.title('Random Forest Feature Importance')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

importance

"""##Lightgbm

"""

!pip install lightgbm -q
from lightgbm import LGBMClassifier

lgbm_param_dist = {
    'n_estimators': [200, 300, 500, 700],
    'learning_rate': [0.01, 0.05, 0.1, 0.15],
    'num_leaves': [15, 31, 63, 127],
    'max_depth': [4, 6, 8, -1],
    'min_child_samples': [10, 20, 30],
}

tscv = TimeSeriesSplit(n_splits=3)

lgbm_search = RandomizedSearchCV(
    LGBMClassifier(class_weight='balanced', random_state=42, verbosity=-1),
    param_distributions=lgbm_param_dist,
    n_iter=15,
    cv=tscv,
    scoring='f1',
    random_state=42,
    n_jobs=-1,
    verbose=1
)

lgbm_search.fit(X_train, y_train)

lgbm = lgbm_search.best_estimator_
print("Best params:", lgbm_search.best_params_)

lgbm_pred = lgbm.predict(X_test)
lgbm_proba = lgbm.predict_proba(X_test)[:, 1]

print("Accuracy:", round(accuracy_score(y_test, lgbm_pred), 4))
print("\nClassification Report:")
print(classification_report(y_test, lgbm_pred))

cm_lgbm = confusion_matrix(y_test, lgbm_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm_lgbm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix — LightGBM')
plt.tight_layout()
plt.show()

lgbm_fpr, lgbm_tpr, _ = roc_curve(y_test, lgbm_proba)
lgbm_auc = roc_auc_score(y_test, lgbm_proba)

plt.figure(figsize=(7,5))
plt.plot(lgbm_fpr, lgbm_tpr, label=f'LightGBM (AUC = {lgbm_auc:.3f})')
plt.plot([0,1], [0,1], '--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve — LightGBM')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print("LightGBM ROC-AUC:", round(lgbm_auc, 4))

lgbm_importance = (
    pd.Series(lgbm.feature_importances_, index=features)
    .sort_values(ascending=False)
)

plt.figure(figsize=(8,5))
sns.barplot(x=lgbm_importance.values, y=lgbm_importance.index)
plt.title('LightGBM Feature Importance')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

lgbm_importance

"""## 9. Stacking"""

from sklearn.calibration import CalibratedClassifierCV
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from mlxtend.classifier import StackingClassifier

# Define base models
clf1 = xgb.XGBClassifier(
    n_estimators=100,      # Number of boosting rounds
    learning_rate=0.1,     # Step size shrinkage
    max_depth=5,           # Maximum tree depth
    random_state=42
)
clf2 = RandomForestClassifier(random_state=42, n_jobs=-1)
clf3 = LGBMClassifier(random_state=42, verbosity=-1)

# Calibrated Classifiers for Stacking
# CalibratedClassifierCV ensures that the output probabilities are well-calibrated,
# which is often beneficial for stacking where the meta-model relies on probabilities.
clf1_calibrated = CalibratedClassifierCV(clf1, method='isotonic', cv=5)
clf2_calibrated = CalibratedClassifierCV(clf2, method='isotonic', cv=5)
clf3_calibrated = CalibratedClassifierCV(clf3, method='isotonic', cv=5)

# Define meta-classifier
s_clf = xgb.XGBClassifier(
    n_estimators=100,      # Number of boosting rounds
    learning_rate=0.1,     # Step size shrinkage
    max_depth=5,           # Maximum tree depth
    random_state=42
)
# Build the StackingClassifier
stack = StackingClassifier(
    classifiers=[clf1_calibrated, clf2_calibrated, clf3_calibrated],
    meta_classifier=s_clf,
    use_probas=True,
    average_probas=False,
    verbose=0
)

# Create a pipeline for the stacking model (including scaling)
stack_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('stacking', stack)
])

stack_pipeline.fit(X_train, y_train)

stack_pred = stack_pipeline.predict(X_test)
stack_proba = stack_pipeline.predict_proba(X_test)[:, 1]

print("Accuracy:", round(accuracy_score(y_test, stack_pred), 4))
print("\nClassification Report:")
print(classification_report(y_test, stack_pred))

"""### Stacking — Confusion Matrix"""

cm_stack = confusion_matrix(y_test, stack_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm_stack, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix — Stacking Classifier')
plt.tight_layout()
plt.show()

"""### Stacking — ROC-AUC"""

stack_fpr, stack_tpr, _ = roc_curve(y_test, stack_proba)
stack_auc = roc_auc_score(y_test, stack_proba)

plt.figure(figsize=(7,5))
plt.plot(stack_fpr, stack_tpr, label=f'Stacking Classifier (AUC = {stack_auc:.3f})')
plt.plot([0,1], [0,1], '--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve — Stacking Classifier')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print("Stacking Classifier ROC-AUC:", round(stack_auc, 4))

"""##Comparison Curves"""

comparison.plot(
    kind='bar',
    figsize=(11,6)
)

plt.title(
    'Model Performance Comparison',
    fontsize=14,
    fontweight='bold'
)

plt.ylabel('Score')
plt.xticks(rotation=0)
plt.ylim(0, 1.05)
plt.legend(loc='lower right')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))

plt.plot(
    lr_fpr, lr_tpr,
    label=f'Logistic Regression (AUC = {lr_auc:.3f})'
)

plt.plot(
    rf_fpr, rf_tpr,
    label=f'Random Forest (AUC = {rf_auc:.3f})'
)

plt.plot(
    lgbm_fpr, lgbm_tpr,
    label=f'LightGBM (AUC = {lgbm_auc:.3f})'
)

plt.plot(
    stack_fpr, stack_tpr,
    label=f'Stacking Classifier (AUC = {stack_auc:.3f})'
)

plt.plot(
    [0,1], [0,1],
    '--',
    color='gray',
    label='Random Classifier'
)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison — All Models')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

from sklearn.metrics import precision_score, recall_score, f1_score

comparison = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Random Forest',
        'LightGBM',
        'Stacking Classifier'
    ],

    'Accuracy': [
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, rf_pred),
        accuracy_score(y_test, lgbm_pred),
        accuracy_score(y_test, stack_pred)
    ],

    'Precision': [
        precision_score(y_test, lr_pred),
        precision_score(y_test, rf_pred),
        precision_score(y_test, lgbm_pred),
        precision_score(y_test, stack_pred)
    ],

    'Recall': [
        recall_score(y_test, lr_pred),
        recall_score(y_test, rf_pred),
        recall_score(y_test, lgbm_pred),
        recall_score(y_test, stack_pred)
    ],

    'F1-Score': [
        f1_score(y_test, lr_pred),
        f1_score(y_test, rf_pred),
        f1_score(y_test, lgbm_pred),
        f1_score(y_test, stack_pred)
    ],

    'ROC-AUC': [
        lr_auc,
        rf_auc,
        lgbm_auc,
        stack_auc
    ]

}).set_index('Model').round(4)

comparison